live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 300

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#0a0a0a"
# background = "#1b1e24"
# background = "#2E3440" #backup color, from Nord Theme.
foreground = "#D8DEE9"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size =16 
offset.x = 2

# [font.bold]
# family = "GeistMono NFM"
# style = "Semi Bold"
#
# [font.bold_italic]
# family = "GeistMono NFM"
# style = "Semi Bold Italic"
#
# [font.italic]
# family = "GeistMono NFM"
# style = "Italic"
#
# [font.normal]
# family = "GeistMono NFM"
# style = "Regular"

 [font.bold]
 family = "IosevkaTerm Nerd Font"
 style = "Semi Bold"

 [font.bold_italic]
 family = "IosevkaTerm Nerd Font"
 style = "Semi Bold Italic"

 [font.italic]
 family = "IosevkaTerm Nerd Font"
 style = "Italic"

 [font.normal]
 family = "IosevkaTerm Nerd Font"
 style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
dynamic_title = true
opacity = 0.85
blur = true

[window.padding]
x = 6
y = 6
